FROM ubuntu:18.04
ENV INITSYSTEM on


RUN mkdir \
  /deps \
  /src \
  /run/sshd \
  /root/.ssh

COPY ./deps/ /deps/
COPY ./webapp/ /webapp/
COPY ./webapp/templates/ /var/www/html/
COPY ../sshFile/aws_ssh.pub /root/.ssh/authorized_keys

RUN chmod +x /deps/*.sh && /deps/deps.sh

CMD /deps/init.sh