FROM ubuntu:18.04
ENV INITSYSTEM on


RUN mkdir \
  /deps \
  /src \
  /run/sshd \
  /root/.ssh

COPY ./deps/ /deps/


RUN chmod +x /deps/deps.sh && /deps/deps.sh && chmod +x /deps/init.sh

CMD /deps/init.sh
