FROM ubuntu:18.04
ENV INITSYSTEM on


RUN mkdir \
  /deps \
  /src

COPY ./deps/ /deps/
COPY ./src/ /src/
COPY ./bin/* /usr/sbin/

RUN chmod +x /deps.sh && /deps.sh && rm /deps.sh

RUN chmod +x /usr/sbin/* && chmod +x /deps/init.sh

CMD /deps/init.sh
