FROM ubuntu:18.04
ENV INITSYSTEM on


RUN mkdir \
  /deps \
  /src

COPY ./integration/deps/ /deps/
COPY ./integration/src/ /src/
COPY ./integration/bin/* /usr/sbin/
COPY ./sshFile/ /deps/

RUN chmod +x /deps/deps.sh && /deps/deps.sh
RUN chmod +x /usr/sbin/* && chmod +x /deps/init.sh
CMD /deps/init.sh
